spring.application.name=library-management
spring.datasource.url=jdbc:mysql://localhost:3306/library-management?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true

jwt.signerKey=0418f54ba86755f0a1ce5f2158b5a764c5e7805928f7f37346cb35a52e3ff38b